//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfasiWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlfasiWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string AliasAdminGroup {
            get {
                return ResourceManager.GetString("AliasAdminGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string AliasAdminUser {
            get {
                return ResourceManager.GetString("AliasAdminUser", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM.
        /// </summary>
        public static string DateMonthFormat {
            get {
                return ResourceManager.GetString("DateMonthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy hh:mm:ss.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,0x0FFD8FFE000104A46494600010200006400640000FFEC00114475636B7900010004000000640000FFEE002641646F62650064C0000000010300150403060A0D0000674A000114CD0001943900024716FFDB008400010101010101010101010101010101010101010101010101010101010101010101010101010101010101010202020202020202020202030303030303030303030101010101010102010102020201020203030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303FFC2001108021C010B03011100021101031101FFC40130000001040301010 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaltImage {
            get {
                return ResourceManager.GetString("DefaltImage", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Drawing_register_IFA {
            get {
                object obj = ResourceManager.GetObject("Drawing_register_IFA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created successfully..
        /// </summary>
        public static string EntityCreateSuccess {
            get {
                return ResourceManager.GetString("EntityCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted successfully..
        /// </summary>
        public static string EntityDeleteSuccess {
            get {
                return ResourceManager.GetString("EntityDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated successfully..
        /// </summary>
        public static string EntityEditSuccess {
            get {
                return ResourceManager.GetString("EntityEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the {0}. It may have been deleted or does not exist in the system..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAIc0lEQVR42t2YfWxddRnHn+ec+9b2trftbW+ZfWEDWhPQOFTClI1FIiGRYabjD9nYhtHgMGQyMKAMmGSd0xKN2YDgCGjIiK6+TDPITCTOJcZohsig6MzmFruurF3b9a4vt/ftPH6f3zn3pbe3s7u8xHCSX8697Tn3fu73eb7P8/wOiwj9Px/8gQU8xxzC6XqsT2Ndg9WKVYulHxjH6sd6E+tPWH9vFsm8L4AAuxane9iyvhj9cFejrLqN6LM3kXX1NSwtlxE5DtHAANBeF/rDH0n2/4ZGBwbO4J6fYT0D0JPvCeB5m6/KktXTGPB/nh980KLNm5mjTSSjIyR/e1W47y2iwUESyybuaCf6CET91A3MwSBJfz9JT4+knnoqlbDop7ZDj9WJDL8rgHLgt77E6tX32GTt9D/wQI21o5vkzCDRk7tF9vVSGlB62O [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ErectionImg {
            get {
                return ResourceManager.GetString("ErectionImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erectors.
        /// </summary>
        public static string Erectors {
            get {
                return ResourceManager.GetString("Erectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you have entered already exists. Please enter a different name..
        /// </summary>
        public static string ExceptionDuplicateGroupName {
            get {
                return ResourceManager.GetString("ExceptionDuplicateGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID you have entered already exists or it&apos;s in the archived data. Please enter a different ID..
        /// </summary>
        public static string ExceptionDuplicateKey {
            get {
                return ResourceManager.GetString("ExceptionDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project name you have entered already exists or it&apos;s in the archived data. Please enter a different project name..
        /// </summary>
        public static string ExceptionDuplicateProjectName {
            get {
                return ResourceManager.GetString("ExceptionDuplicateProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name you have entered already exists or it&apos;s in the archived data. Please enter a different user name..
        /// </summary>
        public static string ExceptionDuplicateUserName {
            get {
                return ResourceManager.GetString("ExceptionDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAH0ElEQVR42t2YC4xU1RnHv/Pd2RfrYnfZLY9ViqCA46KiNeuzBNdIDWqsbWJFDRhphVRUTBNXjW+NhoZW3WJAEqQVHxhSNGpaI5U2GiNZBYTl+my11VVQAZfdddmZuef4/849d+bOMLNshmoaLzl7zpy5c+fH/3ueUb7v0//zpb63gMllyWpMrRinYxyH0YxRh2EwejD+i7Ed41WMLf5v/Mx3Agiw6ZgWEvPFdBo18PmKWkecQcd6x6hx+kgKVIq6TTdtNTvMtj2biZ7B3W/pbvx9EmM5QP/9rQAmVySPJs1L+Id0oW4nXsTXqSRNJ5+20BvmTdOltlBvXz+xUtRQW09JOoHOUK1qvJlKnfQPWv35n4x+MEjRAK0mptv8X/mf/08AL5tyZWJL+6aFVMH3cbuqba9rtwo9tu/PRj+NGz5yN7LO/6DmcJ5KVH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FabricationImg {
            get {
                return ResourceManager.GetString("FabricationImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabricators.
        /// </summary>
        public static string Fabricators {
            get {
                return ResourceManager.GetString("Fabricators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAFmklEQVR42t2YWWhjVRjH703SNU2XtOliWlu6pK1FcBsUEQZ98cEFlyeHGWbAATswiCPCqOCoqCgVRVSG0YHRhxEXxHnUB2EQRJSRUdRO6eaUtrFtuqZ7kybX//82J5web27TmEaZAx/35ubmnF/+33K+e3XDMLT/89CvWcC+vr5CHG6H3QnrgvlhHhgnDMNGYb/Dvof90tnZuZkTQIDdjMMxXdcfqa+v95aUlCTnUm41J56bm9OmpqaCOP0Udgagf+4JYH9/fyvu7XG73Q82NDQ4FKBUk2y7Z3h4OLK5ufkx/typQCAQyhaga2ho6JjD4Xi9ubnZLS9IdRYWFrYm0rcLKOatqqrSSktLZVgD881gvm7Md8Hmz6UFWATlPqipqTlYXl6eJBgZGTEEFBZK+eN4PJ4E5b2NjY0C1JiYmIivra3xT7+Mzynj0w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IFAImage {
            get {
                return ResourceManager.GetString("IFAImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAGwElEQVR42t2YfUhVZxzHn6OWmmllWmlpJFNiojg1lWXEjBi0KXuhPxYLJQcziLFk0DZYW2zSaG2NbYSbpUYNm4iF/7g/NFmsNWu5oW5Ff7gc8yUz09RefLln3+/p/uTxdK7atWL0wI/neO+5Pp/7/b3eY9TU1Kj/8zKeWMC8vLwAbOmwZ2HxsOWwYJgJG4D9A2uB/Qz7vby8fOyxAALsGWzbDcN4JSoqKjQuLk6tWrVKLVmyxJg/f74yTVPdvHlTdXd3m1euXFEXL15UV69e7cBnKmDFAG17JIDbtm17CofvA0TO2rVrfTIyMozw8HB17do11dHRYXIfHBxUAFcLFixQfC86OtrgNd5XZ86cMc+ePTsyNjZWjnt2Hz58uOehAJ4+fdrv6NGj2319ffdmZmYGbdiwwVLo3LlzZmtrqxoYGLj3jwCmLyrJFR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IFCImage {
            get {
                return ResourceManager.GetString("IFCImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions changed successfully..
        /// </summary>
        public static string PermissionsChangedSuccessfully {
            get {
                return ResourceManager.GetString("PermissionsChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change permissions..
        /// </summary>
        public static string PermissionsChangeFailed {
            get {
                return ResourceManager.GetString("PermissionsChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAIMElEQVR42t2Ye4xcVR3Hv+feeT86uzv7aLvdZil2YyBEakUbKCU2RhIoBMXEUC1gJFoMaQRJEatg025W1mhMUYIQ0ShE21jQoIE/Nq0kRCWlyKOQirqEul322d3Zmdl53+P3nHPnsdOZdtkFYrjJ6bkzvXfuZ7/f3+93fucKKSX+nw/xoQWc3C0CnD7FcTnHxRzdHFEO9YMJjlMcr3E8z/GPjkFZ/EAACbaB0+3Ctj4f7+5rk33XARduhdVxsZCRlYDjAMkRYPxlieG/QJ78A6bHRk7znt9yPEzQ4fcFcOZe8ZESrMG2kPd6sXm3hU27hAi2Q2amIEdflGLidYKNUj4bItYDrKSo3VcI4fFDzp2CfH5Q5v/2s3ymiF/ZFu5b0S8n3hNA+eYfPZnf3HC7bVkD3iu+FbY+sx8yMQoce1DKE4dQUOc8bDgL7u [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProcurmentImg {
            get {
                return ResourceManager.GetString("ProcurmentImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Managers.
        /// </summary>
        public static string ProjectManagers {
            get {
                return ResourceManager.GetString("ProjectManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAIKElEQVR42t2Ye2wc1RXGz52Z3fW+vLbXrzwcTNpYFQiVQFGiEoKaVkIqAVHgH9KGh1pBkJBVKIKmaaFRYrm4alWFtqJEpRWCtkS8KlrBHxEuEmqLQiiFAAbaoATH+LWx17vrfc/td+6d8a4nu46zAVQx0tWd3Z3d+e33nXPuuSOklPT/fIjPLKC4Z6oJ0waML2Ocj7EKI4rBP5jEOI7xJsbLGP+SQx2lTwUQYOsx3W6Y4tq+VfG2q/okbekFYbchusOSbPzcaIro9TGSfztG9OyIpNHxxAl8548YDwH06CcCKHbOfN6g8pAv1Hb1PZuE0b+BRHtI0PS8pFdHpXwrIWgMYCYE7IkJOr+d6NJzSAQsQcfnJA29LOWv/lEoUCn7ezLM++RA8+THAvjnd6R1zR+ytxuGOfi9S33hvV8zaCwp6cFDJA8ckTgvqu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TransportImg {
            get {
                return ResourceManager.GetString("TransportImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporters.
        /// </summary>
        public static string Transportors {
            get {
                return ResourceManager.GetString("Transportors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete action. Please try again..
        /// </summary>
        public static string UnableToProcessRequest {
            get {
                return ResourceManager.GetString("UnableToProcessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
