

namespace Dinota.Domain
{
    public enum IdTypes
    {
        RouteWeek = 1,
        RouteDay = 2,
        PromotionCode = 3,
        KeyAccountGroup = 4,
        Brand = 5,
        Designation = 6,
        BusinessType = 7,
        OperatorClass = 8,
        Channel = 9,
        SubChannel = 10,
        OrderType = 11,
        ConvenienceLevel = 12,
        Agent = 13,
        AreaSalesManager = 14,
        Competitor = 15,
        Item = 16,
        CompetitorItem = 17,
        KosherType = 18,
        Geo0 = 49,
        Geo1 = 19,
        Geo2 = 20,
        Geo3 = 21,
        Geo4 = 22,
        Geo5 = 23,
        Outlet = 24,
        SamplingResponse = 25,
        ReturnReason = 26,
        ObjectiveResponseGroups = 27,
        ObjectiveResponse = 28,
        Objective = 29,
        CompetIntelCriterion = 30,
        Category = 31,
        Content = 32,
        Solution = 33,
        AgentTargets = 34,
        OutletContact = 35,
        Targets = 36,
        ProfileCall = 37,
        Survey = 38,
        SurveyQuestion = 39,
        SurveyAnswerChoices = 40,
        Calendar = 41,
        RecipeDish = 42,
        RecipeCostingSheets = 43,
        OutletTag = 44,
        ObjectiveSubTasks = 45,
        TouchPointType = 46,
        SalesCycle = 47,
        TopDish = 48,
        PantryLostReason = 50,
        PantryRetentionReason = 51,
        TargetAudience = 52,
        RAPEquipment = 53,
        OutletContent = 54,
        OutletMap = 55,
        JbpUpliftIssueType = 56,
        DiscountTier = 57,
        RAPOperationVolume = 58,
        Promotion = 59,
        CompetitorItemUsageReason = 60,
        ReturnType = 61,
        ConsolOrderType = 62,
        StaffSkill = 63,
        ChefTopology = 64,
        DisplayType = 65,
        Chef = 66,
        DisplayCategory=67,
        PotentialStage = 68,
        CompetitorCampaignType=69
    }
}

/*
 * important: when you add a new Id Type you need to specify the table name in "IdGenerationStrategy" class in 
 * "Dinota.Msm.Data.EF.Context.Internal" namespace
 */