//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinota.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dinota.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAB+9JREFUeNqMV3tQVNcZ/917dxdcBBQfiAgW2SU+FiFaBY2sRqc0TkrUpumYOtOM/SPTaWa00+l0MpNMB6H28Uc6o830MdNpkplQmio1GSsxdGKUtmiNArKIBJWXPBV5LLvs4+7u7e/sQ5ZlAc/Mt3fvOfd8v+99viMdO3YMCww5MzNz28TExAFZlr9DyvL5fAZVVSVN0yQOTa/Xa5z3cHzFtY/5/le3232fewPzMT59+jQkIcCpU6dmLR4/flxesWJlsdvt+oVOpytJT1+pM5nykJ6xBqmpqUhIMECWZAS0ADxeFZN2OwYH+9DRfgcDA/3E91weHR19IyUlpZv84wpC4aGLt1BRUblsyZIlvwkE/N/Pt+TrN1jyYdmYB7+3H3qpFVCbAB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ErectionImg {
            get {
                return ResourceManager.GetString("ErectionImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAACSpJREFUeNqMV3tQVOcV/927d5+AIm/KQ+UpcUEUeYkgNY1Nx/hIo4mpTRw7007HzmjrtJm2SRuQTttMmk41aTvNH7HpBGlUIg4DKq0PMPVVBQQCBJc3C6yysOzCvndvz737YBdImnM9fHfv9X6/8/id830fc/ToUfwfYRMSEvJnZ2f3sCy7jzTJ6XTKHA4Hw/M8Q8JLpVKenttIPqd3dfT7jNVq7adv3V828alTp8AIBpw8eXLJy2PHjrHR0TFFVqvlNxzHlcbGxnBpaRmIjU/EypUrIZfLwDIs3LwbNrsDJqMRExNj6Ovtwfi4lvBtN6anp3+0YsWKIZp/WUPIeHDLvThxoioyPDz8Lbfb9Wq2Oluapc7G+qxMjM2OoWemC5fG2tCt78 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FabricationImg {
            get {
                return ResourceManager.GetString("FabricationImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAACT5JREFUeNqMV3lsFNcd/t7M7BrbHK7B2A7YXDaEYGMIlzkMRKgkESUkoalokdrSP6KqkZIqbdU/ErWAm1aVmkikUatIVRtaETfcCcIcUTncltAUbGM7hjjYBju+8LVeH7veOV6/NzO7NsRK86Sf3szszvu+3/c73hvx4osv4v8MbdasWasGBgZ2aJr2TVqOZVlB0zSFlFJwyEAgIPl8lONT/naS9+9Go9FGvut82cJvvvkmhCJw4MCBL/z40ksvaRkZM4uj0civDMMoycycaeTlLURm9mxMmzYNSUlBaEKDIx2MxkwMhsPo6PgcDbduor29jfijl/r6+l6YOnXqHa4/IRGShzHRD/v3l05PS0v7rePY3y0sKAwsLihEweJFsAc+R6C3Dm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProcurmentImg {
            get {
                return ResourceManager.GetString("ProcurmentImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAACQpJREFUeNqMV3lQVdcd/u599y08BC2rhCVRVuMD3ECigjZObTqWaJraaJxpxnSmk6ZT7XTyX5wMSqbLtHaiSdP2n1pnqjRVqhlGXDp1i1FjFRAI4sImsik78vZ7b7/zFrjCa5oz8+M87rn3fN/5fss5R9q5cyf+T5NTU1OLxsbGNsmy/H1aut/vt/h8PknXdYlNN5vNOp972O5w7AT/P+J2u9v4rfZVEx84cACSILB///5Zg7t27ZITE5NK3G7X+4qilCYnJylZWTlITknD3LlzYbVaIEsyNF2Dx+vDxPg4+voe4m7rbfT29hDfc2F4ePinsbGxnZw/IhGShxJpYO/eyvh58+b9RtPUH+Y78s2LHPlwLMqB52EP0NwMX309fOzV7m4oqa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TransportImg {
            get {
                return ResourceManager.GetString("TransportImg", resourceCulture);
            }
        }
    }
}
